pversion: 0.2

phases:
  pre_build:
    commands:
      - export BUILD_TIME="$(date +%s)"
      - echo $RUN_ENV $RUN_REGION $RUN_SERVICE
  build:
    commands:
      - bash -lc test1.sh
  post_build:
    commands:
      - bash -lc test2.sh

